KMOD=	ipfw3_basic
SRCS=	ip_fw3_basic.c ip_fw3_basic.h
SRCS+=	ip_fw3_log.c ip_fw3_log.h
SRCS+=  ip_fw3_state.c ip_fw3_state.h
SRCS+=  ip_fw3_table.c ip_fw3_table.h
SRCS+=  ip_fw3_sync.c ip_fw3_sync.h
.include <bsd.kmod.mk>
